# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170929_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='latest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
